apiVersion: v1
kind: Service
metadata:
  name: testvandyro
spec:
  selector:
    app: testvandyro
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testvandyro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testvandyro
  template:
    metadata:
      labels:
        app: testvandyro
    spec:
      containers:
        - name: testvandyro
          image: vandy/testvandyro:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MY_SECRET
              value: On3H1torL3sS
          imagePullPolicy: Always